### PR TITLE
docs enhancement

### PR DESCRIPTION
**Pull request by rohanmathur91**
Please review the changes.

### CODE REVIEW

**Review by anupkgurung — COMMENTED** [review]
seems good just wanted to know why fixed width and height for iframe ?won't it be an issue for smaller screens

**Review by maitrakhatri — APPROVED** [review]
looks good to me

**Comment by rohanmathur91** [comment]
@anupkgurung width and height are in %, so it will take of its parent.

**Review by anupkgurung — APPROVED** [review]

**Review by prakashsakari — COMMENTED** [review]
Looks good to me

**Pull request merged**
