### PR TITLE
avatar and bagde components

### PR DESCRIPTION
**Pull request by rohanmathur91**
Please review the avatar and badge component.
image
image

### CODE REVIEW

**Comment by arpit01923** [comment]
Good one; will you put all these in component library

**Review by anupkgurung — APPROVED** [review]
seems all good !!
(exclusive of utility class)

**Comment by HarshithaKonduru214** [comment]
Looks good :)

**Review by HarshithaKonduru214 — APPROVED** [review]

**Comment by rohanmathur91** [comment]
> Good one; will you put all these in component library

Yes.

**Pull request closed without merging**
